# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Jiggie' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jiggie
    pod 'Alamofire', '~> 3.4'
    pod 'SwiftyUserDefaults', '~> 2.2'
    pod 'SwiftHEXColors', '~> 1.0'
    pod 'UIAlertView+Blocks', '~> 0.9'
    pod 'SVProgressHUD', '~> 2.0'
    
  target 'JiggieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JiggieUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
